version: "3.8"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb
    environment:
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://dynamodb:8000

  client:
    build:
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - NODE_ENV=development

  dynamodb:
    image: amazon/dynamodb-local
    container_name: node-api-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
